language: java
jdk:
- openjdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
install: true
script: "./gradlew clean build jacocoTestReport coveralls"
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./publish.sh; fi
env:
  global:
  - CI_NAME=travis-ci
  # coveralls
  - secure: "eIA27RK7BgAcOuyRFKWqN7V8T3Ta5ZcqYPU3NTrg26ljesZLp9kdtdpjxcW+wyhca8ilHG1x/ci+kfSmnxTIrxohfAsPMqCmK0QBxX5CH2b91DxrsadyPMpn602wVU4z/L8POgYnlK+JHS2EO7ZurazkdQtlJ5BFIW7uw4L9rxvU4MWVK3D6zEKX9n0dSRgy+B1zriD9ujok1WaEEVnvjDOxblemYGAOsOl+zyvB+3SfUZ/lgXLFjEgDoHx2MinEtmMT5hX+Hzpd333XrQ8TOTO45LVsZyQnkyMPO9xo6OiFUh5vbNyjRomSVx1jdIGfXE00SkudCCLSeiWtvWHc+xrZ3AboabEgFU5vUwSKyL2uCc/7MeRZI38ZSla4d7QH0zWULDJkF6UgH7GwuYlYmUwhYAnVxUMsaGceGN9ucf3S0YuL1yF3qCbRzKiADrdPxXYJ64kt7yJZsXW6Xv0maFem/zVq2kZJHvSuTbpiWZ2tthTgEMgdTL0Yat9l2umNYGFjuLLcuDndwRLwYyjwgL/M7xhuMK0SlpNI0xBgnUqxi42zH/yKR5A+kWxbC567SxVDPVyOp3sooU1A83AB2sCobsfnywTIV9IwvPtVUE6XPFFvXuasS6p8ZnIHk+RPMBp2CKzJEMGRiMKBH1+uJOpfW2aLlBd6QOqxzMjg1IM="
  # ORG_GRADLE_PROJECT_sonatypeUsername
  - secure: "jk0VbwDr5vtLDYLCoryHTlOgYWJwYHhAFPj9h0iI9Dyb159x5ip9YntHasIN2uUqbD+rgfGW0yJPUYAgSIJQakpAobtek6RpVN1fqDSR0TjO6N9+HNGisVOAkBqeTj46+CHrpv7mArZPezn1lSJP6C1uBaoHSSZS8PRq2fzMYDluCIQPt8LJHP/8Yfhqm40I/5tvpw8YbPBqmr2WmHL0QcAxmj53jsOe6Z4RNn/DLAnC9fiIM88Xia7trFUx/mtjHJEHwsJm/XcNL9lElLhnfA6MMURdM2+MMqBX8y/I3CnAzbVwrExiulik3sPacZnVjGxqcSgnKLjMPxYmKrh7FOUyA0OmS0kiRqmIQTgPdC8jsP1roSDhYUrxu3neac+e3UUdUy0Kae78oarca8Om4sYPfM4rlGRTg9O+Hsyq4ek1/m9dDc9r+VeLxsYUvqlX087ab9RbnsLjyqRdz4dLTEC3R2JCy4lvyAKKiSyePkqHklhMdSklNszmBesYL0jnMnmyQ1RqX/J/IXgo9exAvXOv1FK7Z7yZh92wtviTWl/b4XJtKh2macubXNCseihBiRbvi8lCThSg7DGIL0mIkhpyCmvFMYIG2Vbj/kED34kOITCvSJfshYP532733ym8H3LKfoIihV8KnJFPfZ84aphc4hderr4kdib8aL64BSQ="
  # ORG_GRADLE_PROJECT_sonatypePassword
  - secure: "osfpPxzbwlPSN9x0pCAtkpUmDa+ZMJAMP0/71J3ankl45na07ZS6s6qWSy+QAM6lOLPdxHsXnqAf2+DzAX430qxDD71cpSvZEdhg0w+Ky9HWNmf5W6ARDAocrRce2H7v35PQqNiRrQJzlea+/zoUMsU+HJ1E7s11FCjf5fRNtAJHznQJDMVNRuY9jgr3YrVbR/ZMlTVg7I0cGSefUvrTuSfB3tpO0zSk42N2GUlyBdyLIgwxBddep1wFXnNr+YpekINXMtf6QHxJFzVA9SwKlSBzViatMVdBfCpbLI4siNb2zEHnKlWjOn1EUoVbWEzs8Q+fYaW0oT+XmaURu1RI4oz+UvWnvUfpCx4ceSfxzhkNEEMgKRbyWKYGvBBpKDf10RZiN8JF5K5xHgkCeMJ8jWYStXJnDpVfQ+e35dzjztF5bY8OTlq2Eeh1nZWioa0oYZ0QYal+luNlBN3fGAqkDYjT5Z6EOnqSkO/nLl0FqvR/AlgLhg5R1cK1lB8Z9M6LeQCJqCqNgzf18aR/DLHyhVr1flvoqq76LjxGwESYaBUva1s4A+vs/C+KGTXqNOX6m+UMDdg9NffTrEsJYWBuDTeojwHRb7RKvV62srxteuDrIBpYDCQTDfK8o0CqaHMy+YZtwBjPx+iaVU6gqJzfJpjfwGfWUykDZPhudIo/SbI="
